### ISSUE TITLE
ListView and CardView

### ISSUE THREAD

**Issue by martinmags** [martinmags/july-challenge-tbd#10]

**Comment by nicolegooden** [comment]
I didn't worry about the Card View portion of this because we already have the design for a single card, so card view would consist of those cards displayed in a grid. 

Here is the initial wireframe for the list view:
Those *** notes in the bottom-left corner aren't part of the design; just notes to make the wireframe more clear.
<img width="1134" alt="Screen Shot 2021-07-02 at 12 40 19 PM" src="https://user-images.githubusercontent.com/62262404/124316424-d1d24c00-db32-11eb-9d51-da1631d4c855.png">

**Comment by nicolegooden** [comment]
I will close this issue once we get a chance to discuss this wireframe and make any edits!
